name: YourServiceName Service CI - Production

on:
  pull_request:
    branches: [ production ]

env:
  deploy-port: 5051
  docker-image-name: ${{ github.event.repository.name }}
  APPID: ${{ secrets.APPID }}
  APPSECRET: ${{ secrets.APPSECRET }}

jobs:
  docker:
    name: Docker Build, Push and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check APPID & APPSECRET for dev
        run:  |
          echo "$APPID"
          echo "$APPSECRET"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker-image-name }}:latest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_YIJUNSTUDIO }}
          username: ${{ secrets.USERNAME_YIJUNSTUDIO }}
          key: ${{ secrets.SSHKEY_YIJUNSTUDIO }}
          command_timeout: 60m
          script: |
            echo $GITHUB_SHA
            sudo docker container ls
            echo ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker-image-name }}:latest
            sudo docker container rm --force ${{ env.docker-image-name }}
            sudo docker image rm --force ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker-image-name }}
            sudo docker run --name ${{ env.docker-image-name }} -p ${{ env.deploy-port }}:8888 -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker-image-name }}:latest
